### ISSUE TITLE
Cannot find module 'vitest-fail-on-console'

### ISSUE THREAD

**Issue by kevinpainchaud** [thomasbrodusch/vitest-fail-on-console#17]
#### Description

Since updating from v0.5.1 to v0.6.0, I get a typescript error on import.
It looks like the type declaration file is missing.

#### Expected outcome

No error on import

#### Actual outcome

Following error: `Cannot find module 'vitest-fail-on-console' or its corresponding type declarations.ts(2307)`

### Screenshot

<img width="803" alt="Screenshot 2024-02-29 at 11 29 10" src="https://github.com/thomasbrodusch/vitest-fail-on-console/assets/710892/0cd9c137-5511-47bc-8121-fdbab59072c7">

**Comment by thomasbrodusch** [comment]
Thanks @kevinpainchaud for raising this issue!
I've reproduced the bug and just pushed a fix for it [in this commit](https://github.com/thomasbrodusch/vitest-fail-on-console/commit/4704b608966d4fa07dbf35c787ae6b6fd88d41fe)

New `v0.6.1` is available on NPM - can you have a try and tell me if you still have any error ?

**Comment by thomasbrodusch** [comment]
Thanks @kevinpainchaud for raising this issue!
I've reproduced the bug and just pushed a fix for it [in this commit](https://github.com/thomasbrodusch/vitest-fail-on-console/commit/4704b608966d4fa07dbf35c787ae6b6fd88d41fe)

New `v0.6.1` is available on NPM - can you have a try and tell me if you still have any error ?

**Comment by kevinpainchaud** [comment]
Unfortunately, I still experience the error after upgrading the dependency.

**Comment by thomasbrodusch** [comment]
Ok, I'll investigate it - thank you for your quick reply!

**Comment by thomasbrodusch** [comment]
@kevinpainchaud New `v0.6.2` is available on NPM and should fix it!

Related changes:
https://github.com/thomasbrodusch/vitest-fail-on-console/commit/9a6025381657a5af7820c6babad8cea417357268

**Comment by kevinpainchaud** [comment]
It's resolved! Thank you very much for promptly fix it 🙏

**Comment by thomasbrodusch** [comment]
Glad to hear that  @kevinpainchaud
Thanks a lot for raising that one and for using `vitest-fail-on-console` 🙏
